# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98ee54447d4b65c8ecbd4e4df09882738cc919ccb5520a64dba8701f07e199c3044ba734ae83ab541e1bff4ba09a27a4947aa79e2dcf1ba02f0cccff4c2259da

test:
  secret_key_base: 7451b4455dfa08dc326a4eb95cc667e3b199049d7bfb7b079e9c18b7fe87b9021d80e79139a482a611436c4fe91ccb6a32f57168b4525cd2dc2fe009f3b971fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
